services:
    vsftpd:
      container_name: vsftpd
      image: wildscamp/vsftpd
      hostname: vsftpd
      ports:
        - "21:21"
        - "30000-30009:30000-30009"
      volumes:
        - ./users:/home/virtual
        - ./projects:/home/virtual/www-data/html
        - ./template:/home/virtual/www-data/template

      environment:
        PASV_ADDRESS: 0.0.0.0
        PASV_MIN_PORT: 30000
        PASV_MAX_PORT: 30009
        VSFTPD_USER_1: 'www-data:ftp:33:'
        VSFTPD_USER_2: 'mysql:mysql:999:'
        VSFTPD_USER_3: 'certs:certs:50:'
     